version: '3.8'
services:
  # Redis Service
  redis:
    image: "redis:alpine" # Use a public Redis image to build the redis service
    restart: unless-stopped
    networks:
      - backend

  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: ./service # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    networks:
      - backend

networks:
    # Create a new Docker network.
  backend:
      driver: bridge