version: '3.8'
services:
  # Redis Service
  redis:
    image: redis # Use a public Redis image to build the redis service
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - backend
    volumes:
      - cache:/data

  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: ./app # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      REDIS_URL: redis:6379
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  cache:
    driver: local

networks:
    # Create a new Docker network.
  backend:
      driver: bridge
